# This workflow uses pull_request_target but doesn't checks out PR code from fork, therefore safe to use
name: Auto-Merge PR After Checks

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Enable GitHub Auto-Merge 
        run: gh pr merge ${{ github.event.pull_request.html_url }} --merge --auto
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
