name: Auto-Enable Auto-Merge on Success

on:
  workflow_run:
    workflows: ["Validate Metadata PR"] 
    types:
      - completed

permissions:
  pull-requests: write
  contents: read

jobs:
  auto-merge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Set up GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Find PR associated with the commit
        id: find_pr
        run: |
          PR_JSON=$(gh api repos/${{ github.repository }}/commits/${{ github.event.workflow_run.head_sha }}/pulls \
            --jq '.[0]')
          if [[ -z "$PR_JSON" || "$PR_JSON" == "null" ]]; then
            echo "No pull request found for commit."
            echo "found=no" >> $GITHUB_OUTPUT
            exit 0
          fi

          PR_NUMBER=$(echo "$PR_JSON" | jq '.number')
          echo "Found PR #$PR_NUMBER"
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
          echo "found=yes" >> $GITHUB_OUTPUT

      - name: Enable Auto-Merge
        if: steps.find_pr.outputs.found == 'yes'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.find_pr.outputs.pr_number }}
          merge-method: merge
