name: Generate Migration Reports
on:
  schedule:
    - cron: '5 0 * * *'  # Runs at 00:05 UTC every day
  workflow_dispatch:  
  
permissions:
    contents: write
    pull-requests: write  

jobs:
  call-generate-reports:
    uses: jenkins-infra/plugin-modernizer-tool/.github/workflows/generate-reports.yml@main