name: Update Metadata

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:     

permissions:
    contents: write
    pull-requests: write

jobs:
  call-update-metadata:
    uses: CodexRaunak/plugin-modernizer-tool/.github/workflows/update-metadata.yml@cleanup-metadata