name: Update Metadata

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:     

permissions:
    contents: write
    pull-requests: write

jobs:
  update-metadata:
    uses: CodexRaunak/plugin-modernizer-tool/.github/workflows/update-metadata.yml@metadata-workflow-implementation
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}