name: Validate Metadata

on:
  pull_request:
    branches: [main]
    paths:
        - '**/modernization-metadata/**'

jobs:
  validate-metadata:
    uses: CodexRaunak/plugin-modernizer-tool/.github/workflows/validate-metadata.yml@metadata-workflow-implementation
    with:
      pr_number: ${{ github.event.pull_request.number }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}